### PR TITLE
Add `EXPR=""` syntax for expression

### PR DESCRIPTION
**Pull request by pofigizm**
http://search.cpan.org/~samtregar/HTML-Template-Expr-0.07/Expr.pm

Each diff in expression/ast.json between top half and bottom half is only in column parameter.

### CODE REVIEW

**Comment by agentcooper** [comment]
HTML::Template expressions are not exactly Perl expressions.

**Comment by Lapple** [comment]
Thanks for the PR, I figured out how to do that slightly differently to be able to add quote escaping in the future. Also, I made a separate test file for the feature, since `test/expression/` is intended for testing `PerlExpression` part and literals' support should be covered by another test case.

**Comment by Lapple** [comment]
Pushed in eabbd76, what do you think?

**Comment by agentcooper** [comment]
:+1:

**Comment by pofigizm** [comment]
it's ok

**Comment by Lapple** [comment]
Closing this one then, thank you.

**Pull request closed without merging**
